# Generated by Django 2.2.7 on 2019-11-08 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True, verbose_name='Русское название')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Английское название')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Даты создания')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Лайк')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0234cbf2-1f09-442c-a845-93bc88a44425'), primary_key=True, serialize=False, verbose_name='Интификатор')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('url_prefix', models.CharField(default='https://dw8stlw9qt0iz.cloudfront.net/', max_length=37, verbose_name='Префикс')),
                ('urls_x300', models.TextField(default=None, null=True, verbose_name='Размеры x300')),
                ('urls_x600', models.TextField(default=None, null=True, verbose_name='Размеры x600')),
                ('url_sufix', models.CharField(default='.png', max_length=4, verbose_name='Суфикс')),
                ('role', models.CharField(blank=True, choices=[('о', 'Обложка'), ('б1', 'Блок 1'), ('б2', 'Блок 2'), ('б3', 'Блок 3')], default='о', max_length=2, verbose_name='Позиция')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата обнаружения')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=500, null=True, unique=True, verbose_name='Английский аголовок')),
                ('text_en', models.TextField(null=True, verbose_name='Английский текст')),
                ('title', models.CharField(max_length=500, null=True, unique=True, verbose_name='Заголовок')),
                ('html', models.TextField(null=True, verbose_name='ХТМЛ')),
                ('url', models.URLField(null=True, verbose_name='Источник')),
                ('text', models.TextField(null=True, verbose_name='Русский текст')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата обнаружения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('rewrite_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('Обнаружен', 'FINDED'), ('Опубликован', 'PUBLISHED')], default='Обнаружен', max_length=15, verbose_name='Статус')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Channel', verbose_name='Рубрика')),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Image', verbose_name='Первое изображение')),
            ],
            options={
                'ordering': ['-created_date'],
                'permissions': (('can_mark_returned', 'Can mark returned'),),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True, verbose_name='Русское название')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Английское название')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Даты создания')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Лайк')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter comment about blog here.', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curiosity.Post')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='curiosity.Tag', verbose_name='Хештеги'),
        ),
    ]
