# Generated by Django 2.2.7 on 2019-11-08 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6683195a-3599-404f-a144-46408c95fdff'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
