# Generated by Django 2.2.7 on 2019-11-09 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0002_auto_20191109_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48e442e9-8570-49da-95c5-36d62288ed21'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
