# Generated by Django 2.2.7 on 2019-11-09 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0004_auto_20191109_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72c2e424-71d4-49b1-ba9d-5f4b6d886bee'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
