# Generated by Django 2.2.7 on 2019-11-08 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=2000)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('komu', multiselectfield.db.fields.MultiSelectField(choices=[('Банкам', 'Банкам'), ('Часным', 'Часным лица'), ('Приставам', 'Судебным приставам'), ('Микрофинансам', 'Микрофинансовым организациям'), ('Другое', 'Другое')], error_messages={'invalid_list': 'Введите список значений.', 'required': 'Обязательное поле.'}, help_text='Выберете 1 или более вариантов.', max_length=44, verbose_name='Кому Вы должны ?')),
                ('skolko', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'До 200 000 руб'), (2, 'От 200 000 руб до 500 000 руб'), (3, 'От 500 000 руб до 1 000 000 руб'), (4, 'Более 1 000 000 руб'), (5, 'Более 5 000 000 руб')], error_messages={'required': 'Обязательное поле.'}, help_text='Укажите пожалуйста приблизительный диапазон', max_length=9, verbose_name='Сколько всего Вы должны ?')),
                ('prosrochky', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Нет'), (2, 'Да, до месяца'), (1, 'Да, от месяца до трёх'), (1, 'Более трёх месяцев')], error_messages={'required': 'Обязательное поле.'}, help_text='Или любым другим платежам срок по которым уже наступил.', max_length=7, verbose_name='Есть ли у Вас просрочки по кредитам ?')),
                ('zalogi', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Есть'), (2, 'Нет')], error_messages={'required': 'Обязательное поле.'}, help_text='Например, ипотечная квартира или             автомобиль купленный в автокредит.', max_length=3, verbose_name='Есть ли у Вас имущество в залоге ?')),
                ('name', models.CharField(default='', error_messages={'required': 'Обязательное поле.'}, help_text='Представьтесь пожалуйста,              нам необходимо знать Ваше имя или псевдоним', max_length=200, verbose_name='Как Вас зовут ?')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Обязательное поле.'}, help_text='Введите Ваш номер телефона', max_length=128, verbose_name='Вот и последний шаг.')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=500)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrot.Question')),
            ],
        ),
    ]
